export const ROLES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  DELIVERY_PARTNER: 'DELIVERY_PARTNER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
});

export const ALL_ROLES = Object.values(ROLES);

export const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PREPARING: 'PREPARING',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  ARRIVING: 'ARRIVING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUNDED: 'REFUNDED',
  FAILED: 'FAILED',
});

export const ALL_ORDER_STATUSES = Object.values(ORDER_STATUS);

// Customer-facing happy path used to position the order timeline
export const DELIVERY_TIMELINE = [
  ORDER_STATUS.PENDING,
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.PREPARING,
  ORDER_STATUS.PICKED_UP,
  ORDER_STATUS.OUT_FOR_DELIVERY,
  ORDER_STATUS.DELIVERED,
];

// Valid forward transitions for the delivery partner / store flow
export const STATUS_TRANSITIONS = {
  PENDING: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  PAYMENT_PENDING: [ORDER_STATUS.PAYMENT_CONFIRMED, ORDER_STATUS.FAILED, ORDER_STATUS.CANCELLED],
  PAYMENT_CONFIRMED: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  CONFIRMED: [ORDER_STATUS.PREPARING, ORDER_STATUS.CANCELLED],
  PREPARING: [ORDER_STATUS.READY_FOR_PICKUP, ORDER_STATUS.CANCELLED],
  READY_FOR_PICKUP: [ORDER_STATUS.ASSIGNED, ORDER_STATUS.PICKED_UP, ORDER_STATUS.CANCELLED],
  ASSIGNED: [ORDER_STATUS.PICKED_UP, ORDER_STATUS.CANCELLED],
  PICKED_UP: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.CANCELLED],
  OUT_FOR_DELIVERY: [ORDER_STATUS.ARRIVING, ORDER_STATUS.DELIVERED],
  ARRIVING: [ORDER_STATUS.DELIVERED],
  DELIVERED: [ORDER_STATUS.REFUND_REQUESTED],
  REFUND_REQUESTED: [ORDER_STATUS.REFUNDED],
  CANCELLED: [],
  REFUNDED: [],
  FAILED: [],
};

export const CANCELLABLE_STATUSES = [
  ORDER_STATUS.PENDING,
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.PREPARING,
];

export const PAYMENT_METHODS = Object.freeze({
  COD: 'COD',
  UPI: 'UPI',
  CARD: 'CARD',
  NETBANKING: 'NETBANKING',
  RAZORPAY: 'RAZORPAY',
  STRIPE: 'STRIPE',
  WALLET: 'WALLET',
});

// Map client-provided payment ids (frontend/mobile) to canonical methods.
export const PAYMENT_METHOD_ALIASES = Object.freeze({
  COD: PAYMENT_METHODS.COD,
  cash: PAYMENT_METHODS.COD,
  cashondelivery: PAYMENT_METHODS.COD,
  UPI: PAYMENT_METHODS.UPI,
  RAF: PAYMENT_METHODS.UPI,
  GPAY: PAYMENT_METHODS.UPI,
  GPay: PAYMENT_METHODS.UPI,
  PHONEPE: PAYMENT_METHODS.UPI,
  PAYTM: PAYMENT_METHODS.UPI,
  CARD: PAYMENT_METHODS.CARD,
  CARDS: PAYMENT_METHODS.CARD,
  NETBANKING: PAYMENT_METHODS.NETBANKING,
  netbanking: PAYMENT_METHODS.NETBANKING,
  RAZORPAY: PAYMENT_METHODS.RAZORPAY,
  STRIPE: PAYMENT_METHODS.STRIPE,
  WALLET: PAYMENT_METHODS.WALLET,
  wallet: PAYMENT_METHODS.WALLET,
});

export const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
});

export const COUPON_TYPES = Object.freeze({
  PERCENTAGE: 'percentage',
  FLAT: 'flat',
  FREE_DELIVERY: 'free_delivery',
});

export const SOCKET_EVENTS = Object.freeze({
  ORDER_CREATED: 'order:created',
  ORDER_CONFIRMED: 'order:confirmed',
  ORDER_PREPARING: 'order:preparing',
  ORDER_READY: 'order:ready_for_pickup',
  ORDER_ASSIGNED: 'order:assigned',
  ORDER_PICKED_UP: 'order:picked_up',
  ORDER_OUT_FOR_DELIVERY: 'order:out_for_delivery',
  ORDER_ARRIVING: 'order:arriving',
  ORDER_DELIVERED: 'order:delivered',
  ORDER_CANCELLED: 'order:cancelled',
  ORDER_STATUS: 'order:status',
  DELIVERY_LOCATION: 'delivery:location',
  DELIVERY_ASSIGNMENT: 'delivery:assignment',
  PARTNER_STATUS: 'delivery:partner_status',
  NOTIFICATION: 'notification:new',
});

export const STATUS_TO_EVENT = {
  [ORDER_STATUS.PENDING]: SOCKET_EVENTS.ORDER_CREATED,
  [ORDER_STATUS.CONFIRMED]: SOCKET_EVENTS.ORDER_CONFIRMED,
  [ORDER_STATUS.PREPARING]: SOCKET_EVENTS.ORDER_PREPARING,
  [ORDER_STATUS.READY_FOR_PICKUP]: SOCKET_EVENTS.ORDER_READY,
  [ORDER_STATUS.ASSIGNED]: SOCKET_EVENTS.ORDER_ASSIGNED,
  [ORDER_STATUS.PICKED_UP]: SOCKET_EVENTS.ORDER_PICKED_UP,
  [ORDER_STATUS.OUT_FOR_DELIVERY]: SOCKET_EVENTS.ORDER_OUT_FOR_DELIVERY,
  [ORDER_STATUS.ARRIVING]: SOCKET_EVENTS.ORDER_ARRIVING,
  [ORDER_STATUS.DELIVERED]: SOCKET_EVENTS.ORDER_DELIVERED,
  [ORDER_STATUS.CANCELLED]: SOCKET_EVENTS.ORDER_CANCELLED,
};

export const COLLECTIONS = Object.freeze({
  USERS: 'users',
  ADDRESSES: 'addresses',
  STORES: 'stores',
  CATEGORIES: 'categories',
  PRODUCTS: 'products',
  INVENTORY: 'inventory',
  CARTS: 'carts',
  WISHLISTS: 'wishlists',
  ORDERS: 'orders',
  PAYMENTS: 'payments',
  DELIVERY_PARTNERS: 'deliveryPartners',
  DELIVERY_ASSIGNMENTS: 'deliveryAssignments',
  COUPONS: 'coupons',
  OFFERS: 'offers',
  REVIEWS: 'reviews',
  NOTIFICATIONS: 'notifications',
  SUPPORT_TICKETS: 'supportTickets',
  BANNERS: 'banners',
  SETTINGS: 'settings',
  AUDIT_LOGS: 'auditLogs',
});
